#!/bin/bash
#
# This script is used to make standalone releases into a named directory.
#
unset PYTHONPATH
unset LD_LIBRARY_PATH
export PCDS_CONDA_VER=5.1.1
source /cds/group/pcds/pyps/conda/pcds_conda
mkdir -p $1/src
git clone https://github.com/mcb64/pmgr.git $1/src
cd $1/src
git checkout $2
pip wheel . --no-deps
export WHEEL=`ls $1/src/*whl`
cd ..
mkdir bin
cat >bin/pmgrLauncher.sh <<END
#!/bin/bash
unset PYTHONPATH
unset LD_LIBRARY_PATH
export PCDS_CONDA_VER=5.1.1
source /cds/group/pcds/pyps/conda/pcds_conda
export PYTHONPATH=$WHEEL
python -m pmgr \$*
END
chmod guo+x bin/pmgrLauncher.sh
cat >bin/pmgrUtils.sh <<END
#!/bin/bash
unset PYTHONPATH
unset LD_LIBRARY_PATH
export PCDS_CONDA_VER=5.1.1
source /cds/group/pcds/pyps/conda/pcds_conda
export PYTHONPATH=$WHEEL
python -m pmgr.pmgrUtils \$*
END
chmod guo+x bin/pmgrUtils.sh
cp bin/pmgrLauncher.sh pmgr
