{% set data = load_setup_py_data() %}

package:
  name: pmgr
  version : {{ data.get('version') }}

source:
  path: ..

build:
  number: 1
  script:
    python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python {{PY_VER}}*,>=3.6
    - setuptools

  run:
    - python {{PY_VER}}*,>=3.6
    - pyqt =5.6
    - pyca >=3
    - pykerberos >=1.1.14
    - mysqlclient =1.3.12

test:
  imports:
    - pmgr
  commands:
    - pmgr --help

about:
  home: https://github.com/pcdshub/pmgr
  license: SLAC Open License
  summary:  Parameter Manager for LCLS Device Configurations
