drop table ims_motor_cfg_grp_log;
drop table ims_motor_cfg_grp;
drop table ims_motor_grp_log;
drop table ims_motor_grp;
delete from ims_motor_update where tbl_name like "%_grp%";
drop trigger if exists ims_motor_grp_ins;
drop trigger if exists ims_motor_grp_del;
drop trigger if exists ims_motor_grp_upd;
update ims_motor_name_map set set_order = 1 where db_field_name = "FLD_RC";
update ims_motor_name_map set set_order = 1 where db_field_name = "FLD_SBAS";
update ims_motor_name_map set set_order = 2 where db_field_name = "FLD_BS";
update ims_motor_name_map set set_order = 2 where db_field_name = "FLD_HS";
update ims_motor_name_map set set_order = 2 where db_field_name = "FLD_S";
update ims_motor set FLD_PN = "", FLD_SN = "";
alter table ims_motor
    drop column FLD_DESC, drop column FLD_PORT,  drop column FLD_DHLM, 
    drop column FLD_HLM,  drop column FLD_HOMD,  drop column FLD_LLM, 
    drop column FLD_OFF,  drop column FLD_DLLM,  drop column name;
alter table ims_motor_log
    drop column FLD_DESC, drop column FLD_PORT,  drop column FLD_DHLM, 
    drop column FLD_HLM,  drop column FLD_HOMD,  drop column FLD_LLM, 
    drop column FLD_OFF,  drop column FLD_DLLM,  drop column name;
alter table ims_motor_cfg drop column owner, drop column security;
alter table ims_motor_cfg_log drop column owner, drop column security;
delete from ims_motor where rec_base = "Unknown";
delete from ims_motor where rec_base = "";
delete from ims_motor_name_map where db_field_name = "FLD_DESC";
delete from ims_motor_name_map where db_field_name = "FLD_PORT";
delete from ims_motor_name_map where db_field_name = "FLD_DHLM";
delete from ims_motor_name_map where db_field_name = "FLD_HLM";
delete from ims_motor_name_map where db_field_name = "FLD_HOMD";
delete from ims_motor_name_map where db_field_name = "FLD_LLM";
delete from ims_motor_name_map where db_field_name = "FLD_OFF";
delete from ims_motor_name_map where db_field_name = "FLD_DLLM";
